backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: 'setup'
    label: 'Setup'
    files:
      - label: 'Legion'
        name: 'legion'
        file: 'content/legion.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Post', name: 'post', widget: 'number' }
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Mission', name: 'mission', widget: 'string' }
          - { label: 'Vision', name: 'vision', widget: 'string' }
          - label: 'Post Officers'
            name: 'officers'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Name', name: 'name', widget: 'text' }
              - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'Contact'
        name: 'contact'
        file: 'content/contact.md'
        fields:
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Info', name: 'info', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'City', name: 'city', widget: 'string' }
          - { label: 'State', name: 'state', widget: 'string' }
          - { label: 'Zip', name: 'zip', widget: 'number' }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Cats'
            name: 'cats'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
