backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "setup"
    label: "Setup"
    files:
      - label: "Post Information"
        name: "post"
        file: "content/post.md"
        fields:
          - { label: "Post Number", name: "number", widget: "number" }
          - { label: "Post Name", name: "name", widget: "string" }
      - label: "Theme"
        name: "theme"
        file: "content/theme.md"
        fields:
          - label: "Border Radius"
            name: "radius"
            widget: "select"
            options:
              - { label: "None", value: "rounded-none" }
              - { label: "Small", value: "rounded-sm" }
              - { label: "Default", value: "rounded" }
              - { label: "Medium", value: "rounded-md" }
              - { label: "Large", value: "rounded-lg" }
              - { label: "XL", value: "rounded-xl" }
              - { label: "XXL", value: "rounded-2xl" }
              - { label: "XXXL", value: "rounded-3xl" }
          - label: "Theme Color"
            name: "color"
            widget: "select"
            options:
              [
                "red",
                "orange",
                "amber",
                "yellow",
                "lime",
                "green",
                "emerald",
                "teal",
                "cyan",
                "sky",
                "blue",
                "indigo",
                "violet",
                "purple",
              ]
      - label: "Address"
        name: "address"
        file: "content/address.md"
        fields:
          - { label: "Street", name: "street", widget: "string" }
          - { label: "City", name: "city", widget: "string" }
          - { label: "State", name: "state", widget: "string" }
          - { label: "Zip", name: "zip", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Affiliated Websites"
        name: "affiliated"
        file: "content/affiliated.md"
        fields:
          - name: "lists"
            label: "Lists"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: string }
              - label: "List"
                name: "list"
                widget: list
                fields:
                  - { label: "Text", name: "text", widget: string }
                  - { label: "Link", name: "link", widget: string }
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Social Media Accounts"
            name: "socials"
            widget: list
            fields:
              - { label: "Account", name: "account", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - {
              label: "Hero Image",
              name: "image",
              widget: "image",
              required: true,
            }
          - {
              label: "Hero Tagline",
              name: "tagline",
              widget: "string",
              required: true,
            }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: true,
            }
          - {
              label: "Vision",
              name: "vision",
              widget: "string",
              required: true,
            }
          - {
              label: "Mission",
              name: "mission",
              widget: "string",
              required: true,
            }
          - {
              label: "history",
              name: "history",
              widget: "text",
              required: true,
            }
          - label: "Post Officers"
            name: "officers"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - {
                  label: "Picture",
                  name: "image",
                  widget: "image",
                  required: true,
                }
          - {
              label: "FAQ Description",
              name: "faqDescription",
              widget: "string",
              required: true,
            }
          - label: "FAQ"
            name: "faq"
            widget: list
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "string" }
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
